In [352]:
import numpy as np
import pandas as pd
import datetime 
import csv
import os
import nbimporter
import torch
from torch import nn
import matplotlib.pyplot as plt

#path to curr directory 
dir_path = os.path.dirname(os.path.abspath("import_and_clean.ipynb"))

In [291]:
#mutates the data_f to replace float time info to datetime object format
def createDatetimeColumn(data_f):
    datetime_col = []
    num_rows = len(data_f.index)
    for i in range(0, num_rows):
        datetime_col += [datetime.datetime(int(data_f["#YY"][i]), int(data_f["MM"][i]), int(data_f["DD"][i]), int(data_f["hh"][i]), int(data_f["mm"][i]))]
    datetime_col = pd.DataFrame(datetime_col, columns = ['datetime'])
    data_f = data_f.drop(["#YY", "MM", "DD", "hh", "mm"], 1)
    data_f = pd.concat([data_f, datetime_col], axis = 1)
    return data_f 

#reads the raw NoAA data int
def readData(filePath):
    #read file
    data_f = pd.read_csv(filepath_or_buffer = filePath, header = 0, skiprows = [1], dtype = 'float', delim_whitespace=True, na_values = {"WVHT":"99.00", "MWD":"999.00"})    
    return data_f

#delete undesirable columns from the NoAA data for features and make datetime object
def cleanColumnsFeatures(data_f):
    cleaned_data_f = data_f[["#YY", "MM", "DD", "hh", "mm", "WVHT", "DPD", "APD", "MWD"]]
    cleaned_data_f = createDatetimeColumn(cleaned_data_f)
    cleaned_data_f = cleaned_data_f.dropna()
    cleaned_data_f = cleaned_data_f.reset_index(drop = True)
    return cleaned_data_f

#delete undesirable columns from the NoAA data for features and make datetime object
def cleanColumnsLabels(data_f):
    cleaned_data_f = data_f[["#YY", "MM", "DD", "hh", "mm", "WVHT"]]
    cleaned_data_f = createDatetimeColumn(cleaned_data_f)
    cleaned_data_f = cleaned_data_f.dropna()
    cleaned_data_f = cleaned_data_f.reset_index(drop = True)
    return cleaned_data_f
    
#min-max normalization
def min_max_normalize(data_f, col_name):
    minimum = data_f[col_name].min()
    maximum = data_f[col_name].max()
    
    data_f[col_name] = (data_f[col_name] - minimum) / (maximum - minimum)
    return data_f 


In [292]:

#input: cleaned wave data
#output: a 2d array containing all of the unique hours of observations that appear in the data and the indices]
#at which they appear
def availableDatetimes(data):
    inds = []
    n = 0
    curr_time = data["datetime"][n] 
    while n < data.shape[0]:
        if (data["datetime"][n].hour != curr_time.hour):
            inds += [n]
            curr_time = data["datetime"][n]
            n += 1
            
        elif(data["datetime"][n].hour == curr_time.hour):
            n += 1
            
    data = data.iloc[inds]
    l = len(inds)
    data = data.reset_index(drop=True)
    for i in range(0, l):
        data.at[i, "datetime"] = data.at[i, "datetime"].replace(minute=0)
    
    return data


#input: two datasets containing only the hourly info of the unique observations appearing in the data
#output: a joined array containing only the common observation times
def matchDataByTime2(d1, d2):
    d1 = availableDatetimes(d1)
    d2 = availableDatetimes(d2)
    matched = d1.merge(d2, how = 'inner', on = "datetime")
    return matched
    


In [293]:
#read data from scripps buoys for each year
tp_offshore_data = [readData(dir_path + "/data/46225h201{}.txt".format(x)) for x in range(3, 10)]
#scripps_offshore_data = [readData(dir_path + "/data/46254h201{}.txt".format(x)) for x in range(5, 10)]
scripps_nearshore_data = [readData(dir_path + "/data/ljpc1h201{}.txt".format(x)) for x in range(3, 10)]


tp_offshore_cleaned = pd.concat([cleanColumnsFeatures(x) for x in tp_offshore_data], axis = 0, ignore_index=True)
scripps_nearshore_cleaned = pd.concat([cleanColumnsLabels(x) for x in scripps_nearshore_data], axis = 0, ignore_index=True)
                            
tp_offshore_cleaned = min_max_normalize(tp_offshore_cleaned, "MWD")

In [294]:
matched_label_data = matchDataByTime2(tp_offshore_cleaned, scripps_nearshore_cleaned)

In [325]:
import torch
import numpy as np
from torchvision import datasets


#a WaveDataset class
#inputs: file_lst - a list of cleaned and matched files in the form of pandas dataframes
#, the last of which contains the desired label data in a 1D array (most likely Significant Wave Height)
#replace junk values with NaN

class WaveDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.len = data.shape[0]
        self.data = data
        
        

    def __getitem__(self, index):
        features = torch.tensor(self.data.loc[index, ["WVHT_x", "DPD", "APD", "MWD"]], requires_grad = True).float()
        label = torch.tensor(self.data.loc[index, "WVHT_y"], requires_grad = True).float()
        return features, label 

    def __len__(self):
        return self.len

    

In [343]:
import sklearn 
from sklearn.model_selection import train_test_split

#train/test split
train_set, test_set = train_test_split(matched_label_data, test_size = 0.3, train_size = 0.7)
train_set.reset_index(drop = True, inplace = True)
test_set.reset_index(drop = True, inplace = True) 

first_n = train_set[:1000].reset_index(drop=True)


In [346]:
batch_size = 10
data_loader = torch.utils.data.DataLoader(WaveDataset(train_set), batch_size = 10)

w = torch.normal(0, 0.1, size = (4, 1), requires_grad = True)
b = torch.zeros((1, 1), requires_grad = True)

def update_params_by_grad(params, learning_rate, batch_size):
    with torch.no_grad():
        for param in params:
            param -= param.grad * learning_rate / batch_size
    for param in params:
        param.grad.zero_()
    

def linreg(X, w, b):
    return torch.matmul(X, w) + b

def loss(pred_y, y):
    return (pred_y - y.reshape(pred_y.shape))**2 



num_epochs = 10
learning_rate = 0.0001
batch_size = 128


for epoch in num_epochs:
    for X, y in data_loader:  
        pred = linreg(X, w, b)
        y = y.reshape(pred.shape)
        l_vec = (pred - y)**2 
        l_vec.sum().backward()
        print(w.grad)
        print(w)
        update_params_by_grad([w, b], learning_rate, batch_size)


    

tensor([[ -18.8099],
        [-264.7054],
        [-141.6145],
        [ -11.1041]])
tensor([[ 0.0080],
        [-0.0218],
        [ 0.0038],
        [-0.0083]], requires_grad=True)
tensor([[ -24.4745],
        [-257.7175],
        [-162.5124],
        [ -13.3329]])
tensor([[ 0.0080],
        [-0.0216],
        [ 0.0039],
        [-0.0083]], requires_grad=True)
tensor([[ -12.8407],
        [-198.1842],
        [-123.1115],
        [  -8.2273]])
tensor([[ 0.0080],
        [-0.0214],
        [ 0.0041],
        [-0.0083]], requires_grad=True)
tensor([[ -17.9105],
        [-227.8812],
        [-142.9296],
        [ -11.0354]])
tensor([[ 0.0080],
        [-0.0212],
        [ 0.0042],
        [-0.0083]], requires_grad=True)
tensor([[ -18.0792],
        [-227.2414],
        [-136.0717],
        [ -11.5814]])
tensor([[ 0.0080],
        [-0.0211],
        [ 0.0043],
        [-0.0083]], requires_grad=True)
tensor([[ -30.3505],
        [-291.9934],
        [-171.3581],
        [ -14.2755]])
tenso

tensor([[ -30.4435],
        [-269.8249],
        [-160.3110],
        [ -12.1122]])
tensor([[ 0.0090],
        [-0.0106],
        [ 0.0104],
        [-0.0078]], requires_grad=True)
tensor([[ -19.0549],
        [-190.2642],
        [-109.4821],
        [  -9.4757]])
tensor([[ 0.0090],
        [-0.0103],
        [ 0.0105],
        [-0.0077]], requires_grad=True)
tensor([[ -25.9924],
        [-205.8213],
        [-126.4924],
        [ -11.1877]])
tensor([[ 0.0090],
        [-0.0102],
        [ 0.0106],
        [-0.0077]], requires_grad=True)
tensor([[ -17.1197],
        [-208.6119],
        [-122.1419],
        [  -8.4852]])
tensor([[ 0.0090],
        [-0.0100],
        [ 0.0107],
        [-0.0077]], requires_grad=True)
tensor([[ -20.0449],
        [-202.3816],
        [-126.1929],
        [ -11.0870]])
tensor([[ 0.0090],
        [-0.0099],
        [ 0.0108],
        [-0.0077]], requires_grad=True)
tensor([[ -25.1573],
        [-223.3275],
        [-157.6617],
        [ -13.1965]])
tenso

tensor([[ 0.0096],
        [-0.0035],
        [ 0.0145],
        [-0.0074]], requires_grad=True)
tensor([[ -21.5638],
        [-154.4520],
        [ -98.7816],
        [  -8.1903]])
tensor([[ 0.0096],
        [-0.0034],
        [ 0.0146],
        [-0.0074]], requires_grad=True)
tensor([[ -14.2992],
        [-175.0227],
        [-108.4266],
        [  -8.5612]])
tensor([[ 0.0096],
        [-0.0033],
        [ 0.0146],
        [-0.0074]], requires_grad=True)
tensor([[ -19.0970],
        [-151.9870],
        [ -95.9480],
        [  -8.9965]])
tensor([[ 0.0096],
        [-0.0031],
        [ 0.0147],
        [-0.0074]], requires_grad=True)
tensor([[ -12.5393],
        [-125.8514],
        [ -81.2900],
        [  -7.5679]])
tensor([[ 0.0097],
        [-0.0030],
        [ 0.0148],
        [-0.0074]], requires_grad=True)
tensor([[ -12.7003],
        [-134.0602],
        [ -86.3026],
        [  -7.5949]])
tensor([[ 0.0097],
        [-0.0029],
        [ 0.0149],
        [-0.0074]], requires_grad

tensor([[ -12.4416],
        [-111.9116],
        [ -70.7069],
        [  -7.2236]])
tensor([[ 0.0103],
        [ 0.0032],
        [ 0.0185],
        [-0.0071]], requires_grad=True)
tensor([[  -7.6592],
        [-121.1349],
        [ -65.7764],
        [  -4.4493]])
tensor([[ 0.0103],
        [ 0.0033],
        [ 0.0185],
        [-0.0071]], requires_grad=True)
tensor([[ -29.0050],
        [-189.8193],
        [-118.2878],
        [  -9.9103]])
tensor([[ 0.0103],
        [ 0.0034],
        [ 0.0186],
        [-0.0071]], requires_grad=True)
tensor([[ -22.2558],
        [-165.3758],
        [-113.0785],
        [ -10.6701]])
tensor([[ 0.0103],
        [ 0.0036],
        [ 0.0187],
        [-0.0071]], requires_grad=True)
tensor([[ -11.1634],
        [-119.2796],
        [ -71.1426],
        [  -6.2369]])
tensor([[ 0.0103],
        [ 0.0037],
        [ 0.0188],
        [-0.0071]], requires_grad=True)
tensor([[  -9.8486],
        [-106.6582],
        [ -56.4932],
        [  -4.8684]])
tenso

tensor([[ -6.5771],
        [-89.0382],
        [-51.7799],
        [ -3.7283]])
tensor([[ 0.0107],
        [ 0.0080],
        [ 0.0213],
        [-0.0068]], requires_grad=True)
tensor([[ -23.6897],
        [-151.8989],
        [ -95.2171],
        [  -8.4811]])
tensor([[ 0.0107],
        [ 0.0081],
        [ 0.0214],
        [-0.0068]], requires_grad=True)
tensor([[ -11.8499],
        [-122.0490],
        [ -79.6959],
        [  -6.3180]])
tensor([[ 0.0108],
        [ 0.0082],
        [ 0.0215],
        [-0.0068]], requires_grad=True)
tensor([[ -16.0262],
        [-140.8487],
        [ -75.9034],
        [  -8.0108]])
tensor([[ 0.0108],
        [ 0.0083],
        [ 0.0215],
        [-0.0068]], requires_grad=True)
tensor([[ -21.4710],
        [-151.5774],
        [ -98.3123],
        [  -8.9407]])
tensor([[ 0.0108],
        [ 0.0084],
        [ 0.0216],
        [-0.0068]], requires_grad=True)
tensor([[ -7.2341],
        [-97.1922],
        [-53.3778],
        [ -4.1703]])
tensor([[ 0.0

tensor([[ -12.3902],
        [-124.8185],
        [ -76.0948],
        [  -6.4791]])
tensor([[ 0.0112],
        [ 0.0122],
        [ 0.0238],
        [-0.0066]], requires_grad=True)
tensor([[ -6.7615],
        [-78.7718],
        [-51.8510],
        [ -4.2897]])
tensor([[ 0.0112],
        [ 0.0123],
        [ 0.0239],
        [-0.0066]], requires_grad=True)
tensor([[ -10.1088],
        [-104.7197],
        [ -61.3285],
        [  -5.6312]])
tensor([[ 0.0112],
        [ 0.0123],
        [ 0.0239],
        [-0.0066]], requires_grad=True)
tensor([[ -7.6531],
        [-87.2695],
        [-44.0352],
        [ -3.8668]])
tensor([[ 0.0112],
        [ 0.0124],
        [ 0.0240],
        [-0.0066]], requires_grad=True)
tensor([[ -15.6795],
        [-154.6803],
        [ -97.7446],
        [  -7.8347]])
tensor([[ 0.0112],
        [ 0.0125],
        [ 0.0240],
        [-0.0066]], requires_grad=True)
tensor([[ -5.8929],
        [-55.6051],
        [-33.2477],
        [ -3.2797]])
tensor([[ 0.0112]

tensor([[ -7.1891],
        [-61.5412],
        [-42.6246],
        [ -3.4428]])
tensor([[ 0.0117],
        [ 0.0159],
        [ 0.0261],
        [-0.0064]], requires_grad=True)
tensor([[ -7.9082],
        [-76.7867],
        [-43.0972],
        [ -3.9322]])
tensor([[ 0.0117],
        [ 0.0160],
        [ 0.0262],
        [-0.0064]], requires_grad=True)
tensor([[ -9.1005],
        [-77.4424],
        [-45.2485],
        [ -4.1702]])
tensor([[ 0.0117],
        [ 0.0161],
        [ 0.0262],
        [-0.0064]], requires_grad=True)
tensor([[ -6.2343],
        [-65.0166],
        [-38.8786],
        [ -3.5801]])
tensor([[ 0.0117],
        [ 0.0161],
        [ 0.0262],
        [-0.0064]], requires_grad=True)
tensor([[-13.9359],
        [-98.1163],
        [-64.5210],
        [ -6.2943]])
tensor([[ 0.0117],
        [ 0.0162],
        [ 0.0263],
        [-0.0064]], requires_grad=True)
tensor([[-11.1110],
        [-93.2815],
        [-55.0300],
        [ -5.2539]])
tensor([[ 0.0117],
        [ 

tensor([[ -11.7041],
        [-104.3156],
        [ -60.7519],
        [  -6.0360]])
tensor([[ 0.0121],
        [ 0.0189],
        [ 0.0280],
        [-0.0063]], requires_grad=True)
tensor([[ -4.7752],
        [-29.7524],
        [-21.0306],
        [ -2.2343]])
tensor([[ 0.0121],
        [ 0.0189],
        [ 0.0280],
        [-0.0063]], requires_grad=True)
tensor([[ -1.5934],
        [-18.0043],
        [-12.4563],
        [ -1.0615]])
tensor([[ 0.0121],
        [ 0.0190],
        [ 0.0280],
        [-0.0063]], requires_grad=True)
tensor([[ -14.0751],
        [-102.6163],
        [ -54.9112],
        [  -4.7305]])
tensor([[ 0.0121],
        [ 0.0190],
        [ 0.0280],
        [-0.0063]], requires_grad=True)
tensor([[-13.4952],
        [-87.5601],
        [-54.5832],
        [ -5.4179]])
tensor([[ 0.0121],
        [ 0.0191],
        [ 0.0281],
        [-0.0062]], requires_grad=True)
tensor([[ -7.9747],
        [-73.9131],
        [-41.8953],
        [ -3.8741]])
tensor([[ 0.0121],
  

tensor([[-12.4718],
        [-84.1876],
        [-60.5906],
        [ -5.0247]])
tensor([[ 0.0124],
        [ 0.0213],
        [ 0.0294],
        [-0.0061]], requires_grad=True)
tensor([[ -5.3940],
        [-45.6447],
        [-28.5344],
        [ -2.3092]])
tensor([[ 0.0124],
        [ 0.0213],
        [ 0.0294],
        [-0.0061]], requires_grad=True)
tensor([[ -5.2452],
        [-45.9811],
        [-32.5749],
        [ -3.0706]])
tensor([[ 0.0124],
        [ 0.0214],
        [ 0.0294],
        [-0.0061]], requires_grad=True)
tensor([[ -3.9751],
        [-44.7990],
        [-20.3650],
        [ -1.9475]])
tensor([[ 0.0124],
        [ 0.0214],
        [ 0.0295],
        [-0.0061]], requires_grad=True)
tensor([[ -5.6612],
        [-52.1114],
        [-31.6922],
        [ -2.6080]])
tensor([[ 0.0124],
        [ 0.0214],
        [ 0.0295],
        [-0.0061]], requires_grad=True)
tensor([[ -4.0169],
        [-45.4643],
        [-19.3078],
        [ -1.9749]])
tensor([[ 0.0124],
        [ 

tensor([[ -6.3353],
        [-46.0514],
        [-30.9224],
        [ -3.1935]])
tensor([[ 0.0127],
        [ 0.0232],
        [ 0.0306],
        [-0.0060]], requires_grad=True)
tensor([[ -7.0223],
        [-27.7826],
        [-22.3940],
        [ -2.9992]])
tensor([[ 0.0127],
        [ 0.0232],
        [ 0.0307],
        [-0.0060]], requires_grad=True)
tensor([[ -6.9929],
        [-60.3877],
        [-29.3970],
        [ -3.0841]])
tensor([[ 0.0127],
        [ 0.0232],
        [ 0.0307],
        [-0.0060]], requires_grad=True)
tensor([[-10.4436],
        [-72.7314],
        [-48.6014],
        [ -4.5592]])
tensor([[ 0.0127],
        [ 0.0233],
        [ 0.0307],
        [-0.0060]], requires_grad=True)
tensor([[ -7.1612],
        [-25.2006],
        [-24.0275],
        [ -2.5506]])
tensor([[ 0.0128],
        [ 0.0234],
        [ 0.0307],
        [-0.0060]], requires_grad=True)
tensor([[ -1.9753],
        [-17.1823],
        [-11.3684],
        [ -1.0873]])
tensor([[ 0.0128],
        [ 

tensor([[ 0.0130],
        [ 0.0246],
        [ 0.0315],
        [-0.0059]], requires_grad=True)
tensor([[-12.0966],
        [-49.8529],
        [-40.2866],
        [ -3.7683]])
tensor([[ 0.0130],
        [ 0.0246],
        [ 0.0315],
        [-0.0059]], requires_grad=True)
tensor([[ -6.7395],
        [-74.9339],
        [-39.3290],
        [ -3.3960]])
tensor([[ 0.0130],
        [ 0.0246],
        [ 0.0316],
        [-0.0059]], requires_grad=True)
tensor([[ -7.4463],
        [-33.6571],
        [-27.1065],
        [ -3.4023]])
tensor([[ 0.0130],
        [ 0.0247],
        [ 0.0316],
        [-0.0059]], requires_grad=True)
tensor([[ -1.4597],
        [-14.8050],
        [ -5.1527],
        [ -0.5947]])
tensor([[ 0.0130],
        [ 0.0247],
        [ 0.0316],
        [-0.0059]], requires_grad=True)
tensor([[ -9.5300],
        [-58.5858],
        [-43.6588],
        [ -4.9352]])
tensor([[ 0.0130],
        [ 0.0247],
        [ 0.0316],
        [-0.0059]], requires_grad=True)
tensor([[-14.

tensor([[ -8.2741],
        [-45.3468],
        [-32.6154],
        [ -3.4333]])
tensor([[ 0.0132],
        [ 0.0259],
        [ 0.0324],
        [-0.0058]], requires_grad=True)
tensor([[ -4.6391],
        [-30.9189],
        [-13.6605],
        [ -1.6990]])
tensor([[ 0.0132],
        [ 0.0259],
        [ 0.0324],
        [-0.0058]], requires_grad=True)
tensor([[ 0.2400],
        [25.1660],
        [14.2679],
        [ 0.7776]])
tensor([[ 0.0132],
        [ 0.0260],
        [ 0.0325],
        [-0.0058]], requires_grad=True)
tensor([[ -6.5901],
        [-58.4894],
        [-33.6411],
        [ -2.8117]])
tensor([[ 0.0132],
        [ 0.0260],
        [ 0.0324],
        [-0.0058]], requires_grad=True)
tensor([[-10.3900],
        [-64.8761],
        [-42.2392],
        [ -3.3498]])
tensor([[ 0.0132],
        [ 0.0260],
        [ 0.0325],
        [-0.0058]], requires_grad=True)
tensor([[ -2.4168],
        [-17.3354],
        [-12.9324],
        [ -1.2886]])
tensor([[ 0.0132],
        [ 0.02

tensor([[ -5.8373],
        [-16.1982],
        [ -7.8832],
        [ -2.1556]])
tensor([[ 0.0134],
        [ 0.0270],
        [ 0.0331],
        [-0.0057]], requires_grad=True)
tensor([[ -7.9140],
        [-51.3459],
        [-32.9887],
        [ -3.7307]])
tensor([[ 0.0134],
        [ 0.0270],
        [ 0.0332],
        [-0.0057]], requires_grad=True)
tensor([[ -9.5343],
        [-14.3961],
        [-18.2866],
        [ -2.9427]])
tensor([[ 0.0134],
        [ 0.0271],
        [ 0.0332],
        [-0.0057]], requires_grad=True)
tensor([[ -4.8668],
        [-18.3279],
        [-21.4530],
        [ -2.1846]])
tensor([[ 0.0135],
        [ 0.0271],
        [ 0.0332],
        [-0.0057]], requires_grad=True)
tensor([[ -7.4025],
        [-49.4256],
        [-33.2780],
        [ -3.2086]])
tensor([[ 0.0135],
        [ 0.0271],
        [ 0.0332],
        [-0.0057]], requires_grad=True)
tensor([[ -9.1052],
        [-53.5055],
        [-31.6614],
        [ -3.2771]])
tensor([[ 0.0135],
        [ 

tensor([[ 0.8538],
        [35.7988],
        [16.5123],
        [ 0.4939]])
tensor([[ 0.0137],
        [ 0.0278],
        [ 0.0338],
        [-0.0056]], requires_grad=True)
tensor([[ 1.6626],
        [29.8696],
        [16.6467],
        [ 1.0816]])
tensor([[ 0.0137],
        [ 0.0278],
        [ 0.0337],
        [-0.0056]], requires_grad=True)
tensor([[ 0.3847],
        [21.8697],
        [ 7.6199],
        [ 0.1434]])
tensor([[ 0.0137],
        [ 0.0278],
        [ 0.0337],
        [-0.0056]], requires_grad=True)
tensor([[ -4.2759],
        [-29.8968],
        [-14.5405],
        [ -2.1152]])
tensor([[ 0.0137],
        [ 0.0277],
        [ 0.0337],
        [-0.0056]], requires_grad=True)
tensor([[ -4.9175],
        [-21.3682],
        [-16.0508],
        [ -1.6939]])
tensor([[ 0.0137],
        [ 0.0278],
        [ 0.0337],
        [-0.0056]], requires_grad=True)
tensor([[-16.9273],
        [-38.9682],
        [-30.9712],
        [ -4.1630]])
tensor([[ 0.0137],
        [ 0.0278],
   

tensor([[-3.0642],
        [-7.3919],
        [-3.4650],
        [-1.0977]])
tensor([[ 0.0139],
        [ 0.0285],
        [ 0.0343],
        [-0.0056]], requires_grad=True)
tensor([[-10.1341],
        [-66.5491],
        [-37.4825],
        [ -2.9684]])
tensor([[ 0.0139],
        [ 0.0285],
        [ 0.0343],
        [-0.0056]], requires_grad=True)
tensor([[ -6.4624],
        [-31.0334],
        [-20.8731],
        [ -1.9554]])
tensor([[ 0.0139],
        [ 0.0286],
        [ 0.0343],
        [-0.0056]], requires_grad=True)
tensor([[ -9.1693],
        [-48.2430],
        [-36.6617],
        [ -4.7869]])
tensor([[ 0.0139],
        [ 0.0286],
        [ 0.0343],
        [-0.0056]], requires_grad=True)
tensor([[-6.4598],
        [ 0.8645],
        [-4.1122],
        [-1.2703]])
tensor([[ 0.0139],
        [ 0.0286],
        [ 0.0343],
        [-0.0056]], requires_grad=True)
tensor([[ -4.1038],
        [-28.7031],
        [-17.0027],
        [ -1.7047]])
tensor([[ 0.0139],
        [ 0.0286],

tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0347],
        [-0.0055]], requires_grad=True)
tensor([[-1.4876],
        [-1.2595],
        [-1.8979],
        [-0.3903]])
tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0347],
        [-0.0055]], requires_grad=True)
tensor([[ -2.2390],
        [-10.4398],
        [ -6.0573],
        [ -1.1166]])
tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0347],
        [-0.0055]], requires_grad=True)
tensor([[ 0.4397],
        [24.0289],
        [13.7602],
        [ 0.3019]])
tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0347],
        [-0.0055]], requires_grad=True)
tensor([[-0.2887],
        [25.1183],
        [19.7889],
        [ 0.0428]])
tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0347],
        [-0.0055]], requires_grad=True)
tensor([[-0.1379],
        [15.9261],
        [ 5.0543],
        [-0.0659]])
tensor([[ 0.0140],
        [ 0.0290],
        [ 0.0346],
        [-0.0055]], requires_grad=True)
tensor([[ -8.6092],
        [

tensor([[ 2.0708],
        [35.6487],
        [18.3699],
        [ 0.9962]])
tensor([[ 0.0142],
        [ 0.0296],
        [ 0.0352],
        [-0.0054]], requires_grad=True)
tensor([[ -7.6280],
        [-29.2142],
        [-21.1503],
        [ -3.2675]])
tensor([[ 0.0142],
        [ 0.0296],
        [ 0.0352],
        [-0.0054]], requires_grad=True)
tensor([[-3.9173],
        [ 0.0287],
        [-3.3425],
        [-1.0598]])
tensor([[ 0.0142],
        [ 0.0296],
        [ 0.0352],
        [-0.0054]], requires_grad=True)
tensor([[-13.7370],
        [-51.1035],
        [-33.7078],
        [ -3.6414]])
tensor([[ 0.0143],
        [ 0.0296],
        [ 0.0352],
        [-0.0054]], requires_grad=True)
tensor([[-0.5787],
        [-0.1121],
        [ 5.4240],
        [-0.4397]])
tensor([[ 0.0143],
        [ 0.0297],
        [ 0.0352],
        [-0.0054]], requires_grad=True)
tensor([[-2.6644],
        [23.0209],
        [13.8365],
        [ 0.3326]])
tensor([[ 0.0143],
        [ 0.0297],
       

tensor([[-0.4503],
        [ 1.8685],
        [ 6.9182],
        [ 0.3978]])
tensor([[ 0.0145],
        [ 0.0300],
        [ 0.0355],
        [-0.0054]], requires_grad=True)
tensor([[ -4.3862],
        [-30.5712],
        [-24.3217],
        [ -2.3269]])
tensor([[ 0.0145],
        [ 0.0300],
        [ 0.0355],
        [-0.0054]], requires_grad=True)
tensor([[ -6.2286],
        [-49.2062],
        [-32.2674],
        [ -2.6786]])
tensor([[ 0.0145],
        [ 0.0300],
        [ 0.0355],
        [-0.0054]], requires_grad=True)
tensor([[-12.2093],
        [-81.4775],
        [-37.2587],
        [ -4.9448]])
tensor([[ 0.0145],
        [ 0.0301],
        [ 0.0356],
        [-0.0054]], requires_grad=True)
tensor([[ 2.0704],
        [40.8478],
        [21.1796],
        [ 1.4068]])
tensor([[ 0.0145],
        [ 0.0301],
        [ 0.0356],
        [-0.0054]], requires_grad=True)
tensor([[-5.3102],
        [ 4.9321],
        [-2.7210],
        [-1.6445]])
tensor([[ 0.0145],
        [ 0.0301],
   

tensor([[-0.1070],
        [13.8343],
        [ 7.2657],
        [-0.3399]])
tensor([[ 0.0147],
        [ 0.0306],
        [ 0.0360],
        [-0.0053]], requires_grad=True)
tensor([[ -5.5886],
        [-40.1495],
        [-26.2510],
        [ -2.6176]])
tensor([[ 0.0147],
        [ 0.0306],
        [ 0.0360],
        [-0.0053]], requires_grad=True)
tensor([[ -8.9907],
        [ -5.0992],
        [-11.8185],
        [ -3.2710]])
tensor([[ 0.0147],
        [ 0.0306],
        [ 0.0360],
        [-0.0053]], requires_grad=True)
tensor([[-0.7311],
        [19.8878],
        [10.5797],
        [-0.2747]])
tensor([[ 0.0147],
        [ 0.0306],
        [ 0.0360],
        [-0.0053]], requires_grad=True)
tensor([[-2.3405],
        [-9.5252],
        [-4.9896],
        [-1.0748]])
tensor([[ 0.0147],
        [ 0.0306],
        [ 0.0360],
        [-0.0053]], requires_grad=True)
tensor([[-2.5715],
        [13.1115],
        [13.1469],
        [-0.7478]])
tensor([[ 0.0147],
        [ 0.0306],
       

        [-0.9734]])
tensor([[ 0.0149],
        [ 0.0308],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
tensor([[-18.1284],
        [-53.1219],
        [-37.4488],
        [ -3.6751]])
tensor([[ 0.0149],
        [ 0.0308],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
tensor([[ -5.9829],
        [-27.9323],
        [-20.4487],
        [ -2.3488]])
tensor([[ 0.0149],
        [ 0.0308],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
tensor([[ -4.9762],
        [-32.4902],
        [-20.8313],
        [ -2.4508]])
tensor([[ 0.0149],
        [ 0.0309],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
tensor([[-1.7340],
        [-3.4080],
        [-4.8817],
        [-1.1580]])
tensor([[ 0.0149],
        [ 0.0309],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
tensor([[-1.8803],
        [-3.9222],
        [-8.5282],
        [-1.0441]])
tensor([[ 0.0149],
        [ 0.0309],
        [ 0.0363],
        [-0.0052]], requires_grad=True)
t

tensor([[ -5.5994],
        [-39.5479],
        [-24.0382],
        [ -2.7655]])
tensor([[ 0.0151],
        [ 0.0309],
        [ 0.0365],
        [-0.0052]], requires_grad=True)
tensor([[ 1.1056],
        [34.4721],
        [17.4261],
        [ 0.4422]])
tensor([[ 0.0151],
        [ 0.0309],
        [ 0.0365],
        [-0.0052]], requires_grad=True)
tensor([[ 1.9489],
        [39.4153],
        [21.3273],
        [ 0.8397]])
tensor([[ 0.0151],
        [ 0.0309],
        [ 0.0365],
        [-0.0052]], requires_grad=True)
tensor([[-0.6092],
        [ 7.2771],
        [ 7.8621],
        [-0.2855]])
tensor([[ 0.0151],
        [ 0.0309],
        [ 0.0365],
        [-0.0052]], requires_grad=True)
tensor([[-13.7210],
        [-31.5979],
        [-30.0452],
        [ -3.7344]])
tensor([[ 0.0151],
        [ 0.0309],
        [ 0.0365],
        [-0.0052]], requires_grad=True)
tensor([[-1.3930],
        [17.8427],
        [14.1193],
        [ 0.1325]])
tensor([[ 0.0151],
        [ 0.0309],
       

tensor([[-2.8618],
        [-2.4641],
        [-4.0245],
        [-0.9954]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0.0365],
        [-0.0051]], requires_grad=True)
tensor([[ 1.8412],
        [47.8796],
        [31.2209],
        [ 1.3185]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0.0365],
        [-0.0051]], requires_grad=True)
tensor([[-1.8336],
        [ 8.9093],
        [ 0.6010],
        [-0.6601]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0.0365],
        [-0.0051]], requires_grad=True)
tensor([[ 2.0764],
        [34.8498],
        [24.6700],
        [ 1.4957]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0.0365],
        [-0.0051]], requires_grad=True)
tensor([[-0.3254],
        [ 7.7635],
        [ 8.6633],
        [ 0.1501]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0.0365],
        [-0.0051]], requires_grad=True)
tensor([[ -6.6600],
        [-26.3204],
        [-20.0840],
        [ -2.0333]])
tensor([[ 0.0152],
        [ 0.0308],
        [ 0

tensor([[ -4.4516],
        [-17.0674],
        [-12.8094],
        [ -1.9003]])
tensor([[ 0.0153],
        [ 0.0308],
        [ 0.0366],
        [-0.0051]], requires_grad=True)
tensor([[ 1.5442],
        [38.9686],
        [25.8285],
        [ 1.2197]])
tensor([[ 0.0154],
        [ 0.0308],
        [ 0.0366],
        [-0.0051]], requires_grad=True)
tensor([[ -3.9034],
        [-19.5581],
        [-13.5036],
        [ -1.7073]])
tensor([[ 0.0154],
        [ 0.0308],
        [ 0.0366],
        [-0.0051]], requires_grad=True)
tensor([[-0.8339],
        [ 8.7511],
        [ 6.2179],
        [-0.0252]])
tensor([[ 0.0154],
        [ 0.0308],
        [ 0.0366],
        [-0.0051]], requires_grad=True)
tensor([[-19.7718],
        [-47.3044],
        [-42.5469],
        [ -4.8124]])
tensor([[ 0.0154],
        [ 0.0308],
        [ 0.0366],
        [-0.0051]], requires_grad=True)
tensor([[ -9.8017],
        [-50.2529],
        [-41.0681],
        [ -4.0715]])
tensor([[ 0.0154],
        [ 0.0308],

tensor([[ -3.6959],
        [-14.5046],
        [-16.8271],
        [ -1.9163]])
tensor([[ 0.0155],
        [ 0.0311],
        [ 0.0369],
        [-0.0050]], requires_grad=True)
tensor([[ -3.5645],
        [-15.3399],
        [ -5.8309],
        [ -1.1430]])
tensor([[ 0.0155],
        [ 0.0311],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ -9.2401],
        [-38.9431],
        [-34.9601],
        [ -3.5632]])
tensor([[ 0.0155],
        [ 0.0311],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-1.8614],
        [ 0.5227],
        [-0.6443],
        [-0.9261]])
tensor([[ 0.0156],
        [ 0.0311],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 1.1814],
        [34.5882],
        [21.8969],
        [ 1.2157]])
tensor([[ 0.0156],
        [ 0.0311],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-1.0030],
        [19.6869],
        [ 4.8037],
        [-0.0894]])
tensor([[ 0.0156],
        [ 0.0311],
   

tensor([[ 1.5831],
        [35.6452],
        [16.4154],
        [ 1.0910]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0.0369],
        [-0.0050]], requires_grad=True)
tensor([[-3.5750],
        [34.6328],
        [ 8.8489],
        [ 0.0598]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0.0369],
        [-0.0050]], requires_grad=True)
tensor([[-20.0527],
        [-59.5078],
        [-37.6250],
        [ -5.1341]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0.0369],
        [-0.0050]], requires_grad=True)
tensor([[ 0.5611],
        [28.1824],
        [14.7425],
        [ 0.3885]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 1.0603],
        [33.1443],
        [19.8823],
        [ 0.9765]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0.0369],
        [-0.0050]], requires_grad=True)
tensor([[-3.3208],
        [45.9547],
        [32.0027],
        [ 0.4328]])
tensor([[ 0.0157],
        [ 0.0308],
        [ 0

tensor([[-1.5947],
        [ 0.7605],
        [-4.3661],
        [-0.6588]])
tensor([[ 0.0158],
        [ 0.0307],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-3.5749],
        [ 4.5633],
        [-2.8961],
        [-0.8596]])
tensor([[ 0.0158],
        [ 0.0307],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ -4.1999],
        [-14.0337],
        [-16.1283],
        [ -1.7619]])
tensor([[ 0.0158],
        [ 0.0307],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 0.2751],
        [16.7649],
        [ 9.1025],
        [ 0.1310]])
tensor([[ 0.0158],
        [ 0.0307],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 0.5942],
        [16.7061],
        [10.0319],
        [ 0.3598]])
tensor([[ 0.0158],
        [ 0.0307],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-3.5402],
        [ 7.0664],
        [ 0.1232],
        [-0.5110]])
tensor([[ 0.0158],
        [ 0.0306],
        [ 0

tensor([[ -4.0364],
        [-18.6392],
        [-20.8329],
        [ -2.1418]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 0.8798],
        [25.2952],
        [14.1033],
        [ 0.8548]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-2.4961],
        [ 1.0247],
        [-7.5902],
        [-1.2269]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[ 2.6135],
        [43.0147],
        [25.1455],
        [ 1.6466]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-2.1036],
        [ 7.1996],
        [-2.0017],
        [-0.9582]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0.0370],
        [-0.0050]], requires_grad=True)
tensor([[-6.3125],
        [ 1.4092],
        [-9.2223],
        [-2.0314]])
tensor([[ 0.0160],
        [ 0.0304],
        [ 0

tensor([[-6.8772],
        [ 4.0968],
        [-9.0241],
        [-1.9746]])
tensor([[ 0.0161],
        [ 0.0305],
        [ 0.0371],
        [-0.0049]], requires_grad=True)
tensor([[ -8.4208],
        [-12.9617],
        [-15.6956],
        [ -1.5813]])
tensor([[ 0.0161],
        [ 0.0305],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[ 0.7310],
        [11.2462],
        [ 7.6638],
        [ 0.3041]])
tensor([[ 0.0161],
        [ 0.0305],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-11.7734],
        [-52.9399],
        [-36.0757],
        [ -4.0890]])
tensor([[ 0.0161],
        [ 0.0305],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-0.4476],
        [15.9209],
        [ 5.6781],
        [ 0.3074]])
tensor([[ 0.0161],
        [ 0.0305],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-11.8620],
        [-67.4630],
        [-34.1953],
        [ -3.5458]])
tensor([[ 0.0161],
        [ 0.0305],
   

tensor([[-3.9845],
        [-4.5885],
        [-9.0524],
        [-1.4587]])
tensor([[ 0.0162],
        [ 0.0303],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[ -3.8527],
        [-24.2987],
        [-10.6302],
        [ -1.2534]])
tensor([[ 0.0162],
        [ 0.0303],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-4.9775],
        [16.0289],
        [ 4.9774],
        [-1.2838]])
tensor([[ 0.0162],
        [ 0.0303],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[ -4.7170],
        [-32.4920],
        [-23.0248],
        [ -2.3898]])
tensor([[ 0.0162],
        [ 0.0303],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-16.3501],
        [-34.9869],
        [-31.7868],
        [ -3.2446]])
tensor([[ 0.0162],
        [ 0.0303],
        [ 0.0372],
        [-0.0049]], requires_grad=True)
tensor([[-1.1371],
        [12.7172],
        [ 4.3088],
        [-0.2597]])
tensor([[ 0.0162],
        [ 0.0304],
   

tensor([[ 2.1478],
        [65.6285],
        [40.0621],
        [ 1.7384]])
tensor([[ 0.0164],
        [ 0.0305],
        [ 0.0374],
        [-0.0048]], requires_grad=True)
tensor([[ -2.1860],
        [ -7.2271],
        [-10.0016],
        [ -0.8229]])
tensor([[ 0.0164],
        [ 0.0304],
        [ 0.0374],
        [-0.0048]], requires_grad=True)
tensor([[-14.9915],
        [-25.7235],
        [-27.9224],
        [ -3.3210]])
tensor([[ 0.0164],
        [ 0.0304],
        [ 0.0374],
        [-0.0048]], requires_grad=True)
tensor([[-15.0918],
        [-18.6635],
        [-19.3217],
        [ -3.0438]])
tensor([[ 0.0164],
        [ 0.0305],
        [ 0.0374],
        [-0.0048]], requires_grad=True)
tensor([[-12.4019],
        [-27.3663],
        [-30.8390],
        [ -3.6384]])
tensor([[ 0.0164],
        [ 0.0305],
        [ 0.0374],
        [-0.0048]], requires_grad=True)
tensor([[ 0.7033],
        [26.2241],
        [12.9506],
        [ 0.6853]])
tensor([[ 0.0164],
        [ 0.0305],

tensor([[ 1.8173],
        [41.4208],
        [22.7051],
        [ 1.3302]])
tensor([[ 0.0166],
        [ 0.0305],
        [ 0.0376],
        [-0.0048]], requires_grad=True)
tensor([[ 0.0927],
        [31.9247],
        [16.2841],
        [ 0.6595]])
tensor([[ 0.0166],
        [ 0.0305],
        [ 0.0376],
        [-0.0048]], requires_grad=True)
tensor([[ -6.7776],
        [-54.5467],
        [-26.3250],
        [ -2.7131]])
tensor([[ 0.0166],
        [ 0.0305],
        [ 0.0375],
        [-0.0048]], requires_grad=True)
tensor([[ -6.2742],
        [-33.1932],
        [-18.7410],
        [ -2.1465]])
tensor([[ 0.0166],
        [ 0.0305],
        [ 0.0376],
        [-0.0048]], requires_grad=True)
tensor([[-2.5626],
        [ 9.1861],
        [ 0.5076],
        [-0.5652]])
tensor([[ 0.0166],
        [ 0.0305],
        [ 0.0376],
        [-0.0048]], requires_grad=True)
tensor([[ 1.9407],
        [42.8353],
        [21.9368],
        [ 1.4349]])
tensor([[ 0.0166],
        [ 0.0305],
       

tensor([[ -3.2410],
        [-14.9794],
        [ -7.7577],
        [ -1.2621]])
tensor([[ 0.0167],
        [ 0.0306],
        [ 0.0377],
        [-0.0047]], requires_grad=True)
tensor([[ -4.5671],
        [-14.3424],
        [-10.5741],
        [ -1.9373]])
tensor([[ 0.0167],
        [ 0.0306],
        [ 0.0377],
        [-0.0047]], requires_grad=True)
tensor([[-2.0337],
        [-0.5020],
        [ 2.3505],
        [-0.5028]])
tensor([[ 0.0167],
        [ 0.0306],
        [ 0.0377],
        [-0.0047]], requires_grad=True)
tensor([[ -7.0806],
        [-31.8093],
        [-17.6463],
        [ -2.4935]])
tensor([[ 0.0167],
        [ 0.0306],
        [ 0.0377],
        [-0.0047]], requires_grad=True)
tensor([[ -4.3726],
        [-20.7106],
        [ -9.9756],
        [ -1.5891]])
tensor([[ 0.0167],
        [ 0.0306],
        [ 0.0377],
        [-0.0047]], requires_grad=True)
tensor([[ -2.9920],
        [-13.3104],
        [-10.9971],
        [ -1.8496]])
tensor([[ 0.0167],
        [ 0.03

tensor([[-11.5080],
        [-44.1487],
        [-36.0361],
        [ -4.8249]])
tensor([[ 0.0168],
        [ 0.0305],
        [ 0.0378],
        [-0.0047]], requires_grad=True)
tensor([[-10.5062],
        [-34.6822],
        [-33.7357],
        [ -3.9991]])
tensor([[ 0.0169],
        [ 0.0305],
        [ 0.0378],
        [-0.0047]], requires_grad=True)
tensor([[-10.5888],
        [-75.4066],
        [-49.7991],
        [ -4.9413]])
tensor([[ 0.0169],
        [ 0.0305],
        [ 0.0378],
        [-0.0047]], requires_grad=True)
tensor([[-41.6009],
        [-63.8207],
        [-62.1912],
        [ -6.2652]])
tensor([[ 0.0169],
        [ 0.0306],
        [ 0.0379],
        [-0.0047]], requires_grad=True)
tensor([[ -6.3492],
        [-29.7504],
        [-18.9760],
        [ -2.1749]])
tensor([[ 0.0169],
        [ 0.0306],
        [ 0.0379],
        [-0.0047]], requires_grad=True)
tensor([[ -8.0563],
        [-28.8401],
        [-28.0250],
        [ -4.1314]])
tensor([[ 0.0169],
        [ 

tensor([[ 0.0171],
        [ 0.0305],
        [ 0.0380],
        [-0.0046]], requires_grad=True)
tensor([[ 1.1504],
        [26.7615],
        [14.5003],
        [ 0.7244]])
tensor([[ 0.0171],
        [ 0.0305],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[ 3.5160],
        [68.5823],
        [33.6191],
        [ 2.0298]])
tensor([[ 0.0171],
        [ 0.0305],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[ -2.8123],
        [-21.6621],
        [-14.7593],
        [ -0.9816]])
tensor([[ 0.0170],
        [ 0.0304],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-1.4353],
        [-1.6857],
        [-0.9599],
        [-0.5100]])
tensor([[ 0.0171],
        [ 0.0304],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[ 1.4915],
        [37.6550],
        [18.7982],
        [ 1.2034]])
tensor([[ 0.0171],
        [ 0.0304],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-0.1379],
        [1

tensor([[-1.5459],
        [ 3.9750],
        [ 3.8851],
        [ 0.1331]])
tensor([[ 0.0172],
        [ 0.0302],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-2.2566],
        [25.2047],
        [15.1430],
        [-0.5452]])
tensor([[ 0.0172],
        [ 0.0302],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-20.4799],
        [-91.9278],
        [-64.9734],
        [ -7.1994]])
tensor([[ 0.0172],
        [ 0.0302],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-1.0304],
        [ 3.5259],
        [ 1.9468],
        [-0.3585]])
tensor([[ 0.0172],
        [ 0.0303],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-2.7755],
        [ 4.4282],
        [-0.8798],
        [-0.7924]])
tensor([[ 0.0172],
        [ 0.0303],
        [ 0.0379],
        [-0.0046]], requires_grad=True)
tensor([[-11.3641],
        [-62.8973],
        [-44.7537],
        [ -4.4179]])
tensor([[ 0.0172],
        [ 0.0303],
       

tensor([[-1.4822],
        [ 3.3089],
        [ 4.0702],
        [-0.1282]])
tensor([[ 0.0173],
        [ 0.0303],
        [ 0.0381],
        [-0.0046]], requires_grad=True)
tensor([[ 0.6532],
        [21.5027],
        [ 7.9649],
        [ 0.2061]])
tensor([[ 0.0173],
        [ 0.0303],
        [ 0.0381],
        [-0.0046]], requires_grad=True)
tensor([[-0.0437],
        [37.9013],
        [13.3750],
        [ 0.5577]])
tensor([[ 0.0173],
        [ 0.0303],
        [ 0.0381],
        [-0.0046]], requires_grad=True)
tensor([[ 1.0365],
        [49.6398],
        [24.3657],
        [ 0.9887]])
tensor([[ 0.0173],
        [ 0.0303],
        [ 0.0381],
        [-0.0046]], requires_grad=True)
tensor([[ 1.3446],
        [39.3532],
        [17.6721],
        [ 0.7874]])
tensor([[ 0.0173],
        [ 0.0303],
        [ 0.0381],
        [-0.0046]], requires_grad=True)
tensor([[ 1.5717],
        [39.3849],
        [17.6117],
        [ 1.2451]])
tensor([[ 0.0173],
        [ 0.0302],
        [ 0.038

tensor([[ 0.7248],
        [44.2890],
        [22.8296],
        [ 0.7114]])
tensor([[ 0.0175],
        [ 0.0302],
        [ 0.0382],
        [-0.0045]], requires_grad=True)
tensor([[-10.0040],
        [-56.5248],
        [-31.2648],
        [ -3.5178]])
tensor([[ 0.0175],
        [ 0.0302],
        [ 0.0382],
        [-0.0045]], requires_grad=True)
tensor([[-2.0290],
        [ 4.8200],
        [-3.2378],
        [-0.8564]])
tensor([[ 0.0175],
        [ 0.0302],
        [ 0.0382],
        [-0.0045]], requires_grad=True)
tensor([[ -6.9937],
        [-51.6561],
        [-23.9750],
        [ -2.5973]])
tensor([[ 0.0175],
        [ 0.0302],
        [ 0.0382],
        [-0.0045]], requires_grad=True)
tensor([[-1.7095],
        [14.0130],
        [ 9.1341],
        [ 0.0622]])
tensor([[ 0.0175],
        [ 0.0302],
        [ 0.0382],
        [-0.0045]], requires_grad=True)
tensor([[-11.9082],
        [-17.1984],
        [-16.0619],
        [ -2.5598]])
tensor([[ 0.0175],
        [ 0.0302],
   

tensor([[-10.2971],
        [-27.5161],
        [-26.2170],
        [ -2.4004]])
tensor([[ 0.0176],
        [ 0.0305],
        [ 0.0385],
        [-0.0045]], requires_grad=True)
tensor([[-1.8382],
        [ 8.7220],
        [ 6.6344],
        [-0.4270]])
tensor([[ 0.0177],
        [ 0.0305],
        [ 0.0385],
        [-0.0045]], requires_grad=True)
tensor([[ -5.9412],
        [-26.2457],
        [-16.8548],
        [ -2.1342]])
tensor([[ 0.0177],
        [ 0.0305],
        [ 0.0385],
        [-0.0045]], requires_grad=True)
tensor([[-3.5686],
        [ 0.5895],
        [-4.0935],
        [-1.1798]])
tensor([[ 0.0177],
        [ 0.0305],
        [ 0.0385],
        [-0.0045]], requires_grad=True)
tensor([[-3.8579],
        [-9.4084],
        [-7.4501],
        [-1.4844]])
tensor([[ 0.0177],
        [ 0.0305],
        [ 0.0385],
        [-0.0045]], requires_grad=True)
tensor([[-2.3730],
        [ 1.5847],
        [-5.7635],
        [-0.9918]])
tensor([[ 0.0177],
        [ 0.0305],
       

tensor([[ -6.4069],
        [-17.3798],
        [-15.0340],
        [ -1.6634]])
tensor([[ 0.0177],
        [ 0.0303],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[-19.9128],
        [-73.4481],
        [-39.8597],
        [ -4.8174]])
tensor([[ 0.0178],
        [ 0.0303],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ 3.3112],
        [66.2007],
        [35.8351],
        [ 2.5783]])
tensor([[ 0.0178],
        [ 0.0303],
        [ 0.0385],
        [-0.0044]], requires_grad=True)
tensor([[-0.9115],
        [40.4950],
        [16.6339],
        [-0.0546]])
tensor([[ 0.0178],
        [ 0.0303],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ -5.5779],
        [-29.3669],
        [-25.4507],
        [ -2.9926]])
tensor([[ 0.0178],
        [ 0.0302],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[-7.4144],
        [42.5108],
        [14.7997],
        [-0.2432]])
tensor([[ 0.0178],
        [ 0.0303],
   

tensor([[-0.9029],
        [-1.1205],
        [-4.0120],
        [-0.5988]])
tensor([[ 0.0179],
        [ 0.0300],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ 0.9440],
        [31.8217],
        [15.8297],
        [ 0.3685]])
tensor([[ 0.0179],
        [ 0.0300],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ 1.6272],
        [38.0796],
        [20.1028],
        [ 1.0224]])
tensor([[ 0.0179],
        [ 0.0300],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ 2.5308],
        [58.8120],
        [26.8345],
        [ 1.7101]])
tensor([[ 0.0179],
        [ 0.0300],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ -4.4308],
        [-27.0629],
        [-20.4483],
        [ -2.1377]])
tensor([[ 0.0179],
        [ 0.0299],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[  5.9007],
        [119.7572],
        [ 64.1431],
        [  3.5030]])
tensor([[ 0.0179],
        [ 0.0300],
       

tensor([[-1.9958],
        [-2.1545],
        [-4.1428],
        [-0.6954]])
tensor([[ 0.0180],
        [ 0.0298],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ -7.4554],
        [-41.3180],
        [-23.1807],
        [ -2.5486]])
tensor([[ 0.0180],
        [ 0.0298],
        [ 0.0384],
        [-0.0044]], requires_grad=True)
tensor([[ -6.2563],
        [-15.0694],
        [-14.4979],
        [ -2.4937]])
tensor([[ 0.0180],
        [ 0.0299],
        [ 0.0385],
        [-0.0044]], requires_grad=True)
tensor([[-24.7425],
        [-60.4520],
        [-49.0970],
        [ -6.3761]])
tensor([[ 0.0180],
        [ 0.0299],
        [ 0.0385],
        [-0.0044]], requires_grad=True)
tensor([[ 1.3582],
        [25.5429],
        [17.4467],
        [ 0.8723]])
tensor([[ 0.0180],
        [ 0.0299],
        [ 0.0385],
        [-0.0044]], requires_grad=True)
tensor([[-10.6191],
        [-73.8489],
        [-42.0668],
        [ -3.5310]])
tensor([[ 0.0180],
        [ 0.0299],

tensor([[ 0.0182],
        [ 0.0297],
        [ 0.0385],
        [-0.0043]], requires_grad=True)
tensor([[ -3.5307],
        [-19.8305],
        [-14.6501],
        [ -1.9676]])
tensor([[ 0.0182],
        [ 0.0298],
        [ 0.0385],
        [-0.0043]], requires_grad=True)
tensor([[ -3.5028],
        [-11.4285],
        [ -5.1681],
        [ -1.7957]])
tensor([[ 0.0182],
        [ 0.0298],
        [ 0.0386],
        [-0.0043]], requires_grad=True)
tensor([[-2.2383],
        [ 5.7958],
        [ 3.7344],
        [-0.3996]])
tensor([[ 0.0182],
        [ 0.0298],
        [ 0.0386],
        [-0.0043]], requires_grad=True)
tensor([[ 1.3935],
        [33.2405],
        [19.2260],
        [ 1.0629]])
tensor([[ 0.0182],
        [ 0.0298],
        [ 0.0386],
        [-0.0043]], requires_grad=True)
tensor([[-2.8180],
        [ 6.9138],
        [-3.2002],
        [-0.9175]])
tensor([[ 0.0182],
        [ 0.0298],
        [ 0.0385],
        [-0.0043]], requires_grad=True)
tensor([[ -8.9881],
     

tensor([[-7.1805],
        [-8.7359],
        [-3.4024],
        [-1.7995]])
tensor([[ 0.0184],
        [ 0.0297],
        [ 0.0387],
        [-0.0043]], requires_grad=True)
tensor([[ -6.3562],
        [ -1.9903],
        [-10.3172],
        [ -1.7800]])
tensor([[ 0.0184],
        [ 0.0297],
        [ 0.0387],
        [-0.0043]], requires_grad=True)
tensor([[ -7.7420],
        [-36.4083],
        [-29.2350],
        [ -3.1270]])
tensor([[ 0.0184],
        [ 0.0297],
        [ 0.0387],
        [-0.0043]], requires_grad=True)
tensor([[ -3.5929],
        [-28.4596],
        [-21.7195],
        [ -1.8903]])
tensor([[ 0.0184],
        [ 0.0298],
        [ 0.0387],
        [-0.0043]], requires_grad=True)
tensor([[-6.1488],
        [-5.4589],
        [ 1.0320],
        [-1.0542]])
tensor([[ 0.0184],
        [ 0.0298],
        [ 0.0387],
        [-0.0043]], requires_grad=True)
tensor([[-5.9288],
        [12.8479],
        [ 4.8965],
        [ 0.0664]])
tensor([[ 0.0184],
        [ 0.0298],
   

tensor([[-2.1169],
        [22.1048],
        [ 5.6488],
        [-0.2316]])
tensor([[ 0.0186],
        [ 0.0298],
        [ 0.0389],
        [-0.0042]], requires_grad=True)
tensor([[-0.1102],
        [32.2764],
        [16.0106],
        [ 0.1183]])
tensor([[ 0.0186],
        [ 0.0298],
        [ 0.0389],
        [-0.0042]], requires_grad=True)
tensor([[ 1.8078],
        [42.0072],
        [26.0632],
        [ 1.5928]])
tensor([[ 0.0186],
        [ 0.0298],
        [ 0.0389],
        [-0.0042]], requires_grad=True)
tensor([[ 3.0360],
        [55.1745],
        [29.3098],
        [ 2.1722]])
tensor([[ 0.0186],
        [ 0.0297],
        [ 0.0388],
        [-0.0042]], requires_grad=True)
tensor([[ -6.1649],
        [-26.9390],
        [-14.6009],
        [ -2.1073]])
tensor([[ 0.0186],
        [ 0.0297],
        [ 0.0388],
        [-0.0042]], requires_grad=True)
tensor([[ 1.9742],
        [38.7957],
        [19.9932],
        [ 1.1117]])
tensor([[ 0.0186],
        [ 0.0297],
        [ 0

tensor([[-3.3464],
        [ 0.9125],
        [-5.4726],
        [-1.1683]])
tensor([[ 0.0187],
        [ 0.0297],
        [ 0.0390],
        [-0.0042]], requires_grad=True)
tensor([[ -2.3357],
        [-13.9816],
        [ -6.3220],
        [ -0.2417]])
tensor([[ 0.0187],
        [ 0.0297],
        [ 0.0390],
        [-0.0042]], requires_grad=True)
tensor([[ -6.8033],
        [-23.0458],
        [ -8.2915],
        [ -1.4344]])
tensor([[ 0.0187],
        [ 0.0297],
        [ 0.0390],
        [-0.0042]], requires_grad=True)
tensor([[-13.1804],
        [-33.7944],
        [-27.4040],
        [ -4.0587]])
tensor([[ 0.0187],
        [ 0.0297],
        [ 0.0390],
        [-0.0042]], requires_grad=True)
tensor([[ 1.3614],
        [37.0696],
        [22.6666],
        [ 0.8603]])
tensor([[ 0.0187],
        [ 0.0298],
        [ 0.0390],
        [-0.0042]], requires_grad=True)
tensor([[-20.9225],
        [-24.3530],
        [-34.1724],
        [ -5.2765]])
tensor([[ 0.0187],
        [ 0.0297],

tensor([[ 2.1106],
        [59.2689],
        [33.0100],
        [ 1.5966]])
tensor([[ 0.0189],
        [ 0.0299],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[-5.3535],
        [ 7.9530],
        [ 4.3471],
        [-0.8241]])
tensor([[ 0.0189],
        [ 0.0299],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[ 1.9242],
        [40.8960],
        [22.1363],
        [ 1.0818]])
tensor([[ 0.0189],
        [ 0.0299],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[ -9.0945],
        [-34.0722],
        [-28.0836],
        [ -3.4799]])
tensor([[ 0.0189],
        [ 0.0299],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[ -3.7309],
        [-24.6074],
        [-18.3619],
        [ -2.2307]])
tensor([[ 0.0189],
        [ 0.0299],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[ 2.2543],
        [50.6571],
        [27.8950],
        [ 1.6245]])
tensor([[ 0.0189],
        [ 0.0299],
       

tensor([[ -3.9962],
        [-28.5244],
        [-20.2966],
        [ -2.1300]])
tensor([[ 0.0191],
        [ 0.0298],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[-11.6115],
        [ -5.2149],
        [-20.0702],
        [ -3.2092]])
tensor([[ 0.0191],
        [ 0.0298],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[ -6.5445],
        [-26.9597],
        [-19.2942],
        [ -2.2340]])
tensor([[ 0.0191],
        [ 0.0298],
        [ 0.0394],
        [-0.0041]], requires_grad=True)
tensor([[ 0.3696],
        [32.3514],
        [13.8427],
        [ 0.8679]])
tensor([[ 0.0191],
        [ 0.0299],
        [ 0.0394],
        [-0.0041]], requires_grad=True)
tensor([[-0.8989],
        [10.8817],
        [ 0.0683],
        [-0.8992]])
tensor([[ 0.0191],
        [ 0.0298],
        [ 0.0394],
        [-0.0041]], requires_grad=True)
tensor([[ 1.6848],
        [28.9629],
        [14.5704],
        [ 1.0419]])
tensor([[ 0.0191],
        [ 0.0298],
   

tensor([[-2.2919],
        [16.5720],
        [ 4.5018],
        [-0.6316]])
tensor([[ 0.0192],
        [ 0.0294],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[ -6.6245],
        [-35.0805],
        [-28.1890],
        [ -3.4285]])
tensor([[ 0.0192],
        [ 0.0294],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[ 0.8538],
        [53.8850],
        [34.5188],
        [ 1.3467]])
tensor([[ 0.0192],
        [ 0.0295],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[ 2.0537],
        [33.8445],
        [17.6838],
        [ 1.4293]])
tensor([[ 0.0192],
        [ 0.0294],
        [ 0.0393],
        [-0.0041]], requires_grad=True)
tensor([[ 2.7798],
        [50.0147],
        [31.0281],
        [ 1.2416]])
tensor([[ 0.0192],
        [ 0.0294],
        [ 0.0392],
        [-0.0041]], requires_grad=True)
tensor([[-2.4352],
        [-3.0252],
        [ 2.0249],
        [-0.1255]])
tensor([[ 0.0192],
        [ 0.0294],
        [ 0

tensor([[ -4.6758],
        [-21.1887],
        [-12.7110],
        [ -1.7739]])
tensor([[ 0.0194],
        [ 0.0296],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ -6.8067],
        [-22.5310],
        [-21.1132],
        [ -2.8549]])
tensor([[ 0.0194],
        [ 0.0296],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[-1.4923],
        [ 6.8355],
        [ 0.7897],
        [-0.5284]])
tensor([[ 0.0194],
        [ 0.0296],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ -5.7424],
        [-17.7988],
        [-16.5446],
        [ -2.2884]])
tensor([[ 0.0194],
        [ 0.0296],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ -4.6500],
        [-14.4483],
        [-13.8511],
        [ -1.3604]])
tensor([[ 0.0194],
        [ 0.0296],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ -4.7467],
        [-21.1363],
        [-15.7351],
        [ -1.7710]])
tensor([[ 0.0194],
        [ 0.02

tensor([[ 1.4695],
        [40.2054],
        [23.1042],
        [ 1.4931]])
tensor([[ 0.0195],
        [ 0.0297],
        [ 0.0397],
        [-0.0040]], requires_grad=True)
tensor([[ -3.4560],
        [-12.8984],
        [-11.0312],
        [ -1.3396]])
tensor([[ 0.0195],
        [ 0.0296],
        [ 0.0397],
        [-0.0040]], requires_grad=True)
tensor([[-0.3041],
        [22.4284],
        [11.4270],
        [ 0.3740]])
tensor([[ 0.0195],
        [ 0.0296],
        [ 0.0397],
        [-0.0040]], requires_grad=True)
tensor([[-11.2213],
        [-63.7074],
        [-39.6386],
        [ -4.1241]])
tensor([[ 0.0195],
        [ 0.0296],
        [ 0.0396],
        [-0.0040]], requires_grad=True)
tensor([[-3.7487],
        [13.0480],
        [-1.4886],
        [-0.4495]])
tensor([[ 0.0195],
        [ 0.0297],
        [ 0.0397],
        [-0.0040]], requires_grad=True)
tensor([[ -1.7555],
        [-11.2893],
        [ -8.4546],
        [ -0.8751]])
tensor([[ 0.0195],
        [ 0.0297],
   

tensor([[ 2.2110],
        [45.0331],
        [28.4801],
        [ 1.0686]])
tensor([[ 0.0196],
        [ 0.0292],
        [ 0.0396],
        [-0.0039]], requires_grad=True)
tensor([[ -5.4721],
        [-15.3466],
        [-10.6531],
        [ -1.4986]])
tensor([[ 0.0196],
        [ 0.0292],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ 0.2267],
        [23.3098],
        [19.0578],
        [ 0.6274]])
tensor([[ 0.0196],
        [ 0.0292],
        [ 0.0395],
        [-0.0039]], requires_grad=True)
tensor([[-0.9697],
        [26.2994],
        [10.5546],
        [ 0.5146]])
tensor([[ 0.0196],
        [ 0.0292],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ -6.8471],
        [-40.3494],
        [-28.1362],
        [ -3.4392]])
tensor([[ 0.0196],
        [ 0.0292],
        [ 0.0395],
        [-0.0040]], requires_grad=True)
tensor([[ 0.9813],
        [39.5456],
        [17.9855],
        [ 0.9814]])
tensor([[ 0.0196],
        [ 0.0292],
       

tensor([[ 0.0198],
        [ 0.0291],
        [ 0.0396],
        [-0.0039]], requires_grad=True)
tensor([[-4.9506],
        [-1.9614],
        [-8.1952],
        [-2.2418]])
tensor([[ 0.0198],
        [ 0.0292],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[ 0.6889],
        [27.7005],
        [11.2358],
        [ 0.9613]])
tensor([[ 0.0198],
        [ 0.0292],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[-10.0359],
        [-30.5365],
        [-21.3828],
        [ -2.8432]])
tensor([[ 0.0198],
        [ 0.0291],
        [ 0.0396],
        [-0.0039]], requires_grad=True)
tensor([[-10.3742],
        [-57.8430],
        [-39.0731],
        [ -4.4399]])
tensor([[ 0.0198],
        [ 0.0292],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[-3.7368],
        [ 7.4510],
        [-4.9239],
        [-1.2900]])
tensor([[ 0.0198],
        [ 0.0292],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[ 1.3021],
      

tensor([[-1.8751],
        [ 0.1640],
        [-2.8368],
        [-0.7899]])
tensor([[ 0.0199],
        [ 0.0290],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[ -5.4825],
        [-32.4482],
        [-26.8264],
        [ -3.0152]])
tensor([[ 0.0199],
        [ 0.0290],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[-1.4454],
        [12.7570],
        [ 2.9195],
        [-1.1711]])
tensor([[ 0.0199],
        [ 0.0290],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[-15.4193],
        [-48.2140],
        [-40.3713],
        [ -4.3619]])
tensor([[ 0.0199],
        [ 0.0290],
        [ 0.0397],
        [-0.0039]], requires_grad=True)
tensor([[-1.1505],
        [21.1494],
        [ 7.1418],
        [-0.1499]])
tensor([[ 0.0200],
        [ 0.0291],
        [ 0.0398],
        [-0.0039]], requires_grad=True)
tensor([[-30.8102],
        [-56.8285],
        [-45.3286],
        [ -4.8292]])
tensor([[ 0.0200],
        [ 0.0290],
   

tensor([[ -6.6395],
        [-41.7108],
        [-27.6417],
        [ -3.1983]])
tensor([[ 0.0201],
        [ 0.0289],
        [ 0.0398],
        [-0.0038]], requires_grad=True)
tensor([[ 0.4084],
        [24.0060],
        [10.1249],
        [ 0.6726]])
tensor([[ 0.0201],
        [ 0.0290],
        [ 0.0398],
        [-0.0038]], requires_grad=True)
tensor([[ -7.6713],
        [-37.9893],
        [-29.9466],
        [ -3.3244]])
tensor([[ 0.0201],
        [ 0.0290],
        [ 0.0398],
        [-0.0038]], requires_grad=True)
tensor([[ -8.8691],
        [-29.7239],
        [-27.0006],
        [ -3.9000]])
tensor([[ 0.0201],
        [ 0.0290],
        [ 0.0399],
        [-0.0038]], requires_grad=True)
tensor([[ -7.5774],
        [-28.7475],
        [-18.2881],
        [ -2.4083]])
tensor([[ 0.0201],
        [ 0.0290],
        [ 0.0399],
        [-0.0038]], requires_grad=True)
tensor([[ -8.7398],
        [-43.3913],
        [-27.9269],
        [ -2.9723]])
tensor([[ 0.0201],
        [ 0.02

tensor([[-1.8946],
        [ 5.5286],
        [-2.1594],
        [-0.7227]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0.0401],
        [-0.0038]], requires_grad=True)
tensor([[-4.1257],
        [-2.5905],
        [-6.3927],
        [-1.2765]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0.0401],
        [-0.0038]], requires_grad=True)
tensor([[-3.2857],
        [11.6852],
        [ 1.4688],
        [-1.4198]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0.0401],
        [-0.0038]], requires_grad=True)
tensor([[-1.0688],
        [13.3893],
        [ 9.6420],
        [-0.1329]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0.0401],
        [-0.0038]], requires_grad=True)
tensor([[ -4.7491],
        [-11.5221],
        [-12.0168],
        [ -1.8823]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0.0401],
        [-0.0038]], requires_grad=True)
tensor([[ 0.1970],
        [15.1759],
        [ 6.8638],
        [ 0.2664]])
tensor([[ 0.0203],
        [ 0.0292],
        [ 0

tensor([[-5.3845],
        [12.5143],
        [-1.3265],
        [-1.3530]])
tensor([[ 0.0205],
        [ 0.0293],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[ -2.2939],
        [-12.1606],
        [ -8.5022],
        [ -1.6014]])
tensor([[ 0.0205],
        [ 0.0293],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[-0.5930],
        [36.5870],
        [25.2914],
        [ 0.6689]])
tensor([[ 0.0205],
        [ 0.0293],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[ -6.7953],
        [-20.3715],
        [-18.4233],
        [ -2.5350]])
tensor([[ 0.0205],
        [ 0.0293],
        [ 0.0402],
        [-0.0037]], requires_grad=True)
tensor([[ -7.1074],
        [ -6.8283],
        [-11.6943],
        [ -2.8324]])
tensor([[ 0.0205],
        [ 0.0293],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[-0.5080],
        [16.7823],
        [ 5.0671],
        [ 0.2380]])
tensor([[ 0.0205],
        [ 0.0293],
   

tensor([[-2.4051],
        [ 2.8111],
        [ 0.3555],
        [-0.4663]])
tensor([[ 0.0206],
        [ 0.0290],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[ -9.0456],
        [-34.3613],
        [-25.8139],
        [ -3.3448]])
tensor([[ 0.0206],
        [ 0.0290],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[-0.3417],
        [15.6212],
        [10.8115],
        [ 0.6365]])
tensor([[ 0.0206],
        [ 0.0290],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[ 1.8519],
        [38.8220],
        [26.2060],
        [ 1.0890]])
tensor([[ 0.0206],
        [ 0.0290],
        [ 0.0403],
        [-0.0037]], requires_grad=True)
tensor([[ 4.1272],
        [72.4954],
        [48.8894],
        [ 2.9229]])
tensor([[ 0.0206],
        [ 0.0290],
        [ 0.0402],
        [-0.0037]], requires_grad=True)
tensor([[-8.1605],
        [-6.5534],
        [-3.1640],
        [-1.9407]])
tensor([[ 0.0206],
        [ 0.0289],
        [ 0

tensor([[ 0.0207],
        [ 0.0287],
        [ 0.0401],
        [-0.0037]], requires_grad=True)
tensor([[ 1.6246],
        [32.2234],
        [20.9553],
        [ 0.8818]])
tensor([[ 0.0207],
        [ 0.0287],
        [ 0.0402],
        [-0.0037]], requires_grad=True)
tensor([[-3.4758],
        [22.5743],
        [14.0799],
        [-0.4538]])
tensor([[ 0.0207],
        [ 0.0287],
        [ 0.0401],
        [-0.0037]], requires_grad=True)
tensor([[ 1.9103],
        [31.0250],
        [17.8081],
        [ 1.2559]])
tensor([[ 0.0207],
        [ 0.0287],
        [ 0.0401],
        [-0.0037]], requires_grad=True)
tensor([[-0.4723],
        [31.2315],
        [15.4390],
        [ 0.1734]])
tensor([[ 0.0207],
        [ 0.0287],
        [ 0.0401],
        [-0.0037]], requires_grad=True)
tensor([[ -5.9132],
        [-30.6479],
        [-12.9748],
        [ -2.0808]])
tensor([[ 0.0207],
        [ 0.0286],
        [ 0.0401],
        [-0.0037]], requires_grad=True)
tensor([[-6.0834],
        [ 

tensor([[ -5.1009],
        [ -3.4138],
        [-11.0955],
        [ -1.9558]])
tensor([[ 0.0208],
        [ 0.0288],
        [ 0.0403],
        [-0.0036]], requires_grad=True)
tensor([[-1.8234],
        [-1.3011],
        [-4.1113],
        [-0.7881]])
tensor([[ 0.0208],
        [ 0.0288],
        [ 0.0403],
        [-0.0036]], requires_grad=True)
tensor([[ -7.6560],
        [-41.9233],
        [-25.9268],
        [ -2.9104]])
tensor([[ 0.0208],
        [ 0.0288],
        [ 0.0403],
        [-0.0036]], requires_grad=True)
tensor([[ 1.5254],
        [40.5706],
        [19.3787],
        [ 0.8508]])
tensor([[ 0.0208],
        [ 0.0288],
        [ 0.0403],
        [-0.0036]], requires_grad=True)
tensor([[-16.6206],
        [-81.4903],
        [-49.6307],
        [ -5.0269]])
tensor([[ 0.0208],
        [ 0.0288],
        [ 0.0403],
        [-0.0036]], requires_grad=True)
tensor([[ 1.1340],
        [34.3763],
        [17.1192],
        [ 1.2423]])
tensor([[ 0.0208],
        [ 0.0288],
   

tensor([[-2.4110],
        [ 1.0105],
        [ 3.4434],
        [-0.5425]])
tensor([[ 0.0209],
        [ 0.0286],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[-5.2747],
        [-7.2590],
        [-9.2603],
        [-2.1799]])
tensor([[ 0.0210],
        [ 0.0286],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ -7.1704],
        [  1.7537],
        [-12.4263],
        [ -1.6065]])
tensor([[ 0.0210],
        [ 0.0286],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ 1.4374],
        [34.0415],
        [21.5177],
        [ 1.1209]])
tensor([[ 0.0210],
        [ 0.0286],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[-0.8545],
        [ 3.3401],
        [ 4.3027],
        [ 0.2978]])
tensor([[ 0.0210],
        [ 0.0286],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ -7.8931],
        [-23.0724],
        [-21.8842],
        [ -2.4979]])
tensor([[ 0.0210],
        [ 0.0286],
       

tensor([[-7.5626],
        [ 2.2371],
        [-6.8030],
        [-2.2910]])
tensor([[ 0.0211],
        [ 0.0285],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[-1.6644],
        [ 6.2083],
        [ 6.3425],
        [-0.0742]])
tensor([[ 0.0211],
        [ 0.0285],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ 0.2870],
        [28.2187],
        [ 8.8868],
        [ 0.5446]])
tensor([[ 0.0211],
        [ 0.0285],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ -3.7442],
        [-16.3141],
        [-17.5847],
        [ -1.5715]])
tensor([[ 0.0211],
        [ 0.0285],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ -5.8412],
        [-27.6627],
        [-14.5092],
        [ -2.1154]])
tensor([[ 0.0211],
        [ 0.0285],
        [ 0.0404],
        [-0.0036]], requires_grad=True)
tensor([[ -4.0456],
        [-11.9493],
        [ -2.3650],
        [ -0.9420]])
tensor([[ 0.0211],
        [ 0.0285],
   

tensor([[ 0.8763],
        [25.0490],
        [11.9872],
        [ 0.6089]])
tensor([[ 0.0213],
        [ 0.0287],
        [ 0.0406],
        [-0.0035]], requires_grad=True)
tensor([[-3.9353],
        [-4.3739],
        [-9.9595],
        [-1.5537]])
tensor([[ 0.0213],
        [ 0.0286],
        [ 0.0406],
        [-0.0035]], requires_grad=True)
tensor([[-2.5224],
        [ 5.1364],
        [-4.1626],
        [-0.2880]])
tensor([[ 0.0213],
        [ 0.0287],
        [ 0.0406],
        [-0.0035]], requires_grad=True)
tensor([[ 0.1290],
        [35.7143],
        [17.7659],
        [ 0.1312]])
tensor([[ 0.0213],
        [ 0.0286],
        [ 0.0406],
        [-0.0035]], requires_grad=True)
tensor([[-13.2542],
        [-57.1021],
        [-46.1009],
        [ -4.1550]])
tensor([[ 0.0213],
        [ 0.0286],
        [ 0.0406],
        [-0.0035]], requires_grad=True)
tensor([[ 1.3595],
        [21.6353],
        [17.5714],
        [ 1.2072]])
tensor([[ 0.0213],
        [ 0.0287],
        [ 0

tensor([[ 0.0215],
        [ 0.0286],
        [ 0.0407],
        [-0.0035]], requires_grad=True)
tensor([[-0.4259],
        [14.0733],
        [ 7.8480],
        [ 0.2194]])
tensor([[ 0.0215],
        [ 0.0287],
        [ 0.0408],
        [-0.0035]], requires_grad=True)
tensor([[ 0.9011],
        [29.8881],
        [22.1289],
        [ 0.6376]])
tensor([[ 0.0215],
        [ 0.0287],
        [ 0.0408],
        [-0.0035]], requires_grad=True)
tensor([[-12.7158],
        [-52.3884],
        [-39.2177],
        [ -4.0991]])
tensor([[ 0.0215],
        [ 0.0286],
        [ 0.0407],
        [-0.0035]], requires_grad=True)
tensor([[-13.8175],
        [-53.8114],
        [-38.3074],
        [ -4.4078]])
tensor([[ 0.0215],
        [ 0.0287],
        [ 0.0408],
        [-0.0035]], requires_grad=True)
tensor([[ -4.0236],
        [-15.8228],
        [-14.4907],
        [ -1.5323]])
tensor([[ 0.0215],
        [ 0.0287],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[-1.1848],
  

tensor([[ 1.1870],
        [22.0887],
        [13.7263],
        [ 0.4629]])
tensor([[ 0.0216],
        [ 0.0286],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[-7.8335],
        [-2.5742],
        [-0.8137],
        [-1.4480]])
tensor([[ 0.0216],
        [ 0.0285],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[ -3.7452],
        [-18.7133],
        [-11.4733],
        [ -1.6097]])
tensor([[ 0.0216],
        [ 0.0285],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[-18.8036],
        [-74.3316],
        [-59.6614],
        [ -6.6275]])
tensor([[ 0.0216],
        [ 0.0286],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[-0.2276],
        [23.7545],
        [15.5029],
        [ 0.5499]])
tensor([[ 0.0216],
        [ 0.0286],
        [ 0.0409],
        [-0.0034]], requires_grad=True)
tensor([[-3.6170],
        [ 2.4648],
        [ 3.4952],
        [-1.0636]])
tensor([[ 0.0216],
        [ 0.0286],
       

tensor([[ -8.5178],
        [ -3.2240],
        [-13.0254],
        [ -2.5554]])
tensor([[ 0.0217],
        [ 0.0284],
        [ 0.0409],
        [-0.0034]], requires_grad=True)
tensor([[-2.1055],
        [23.1116],
        [ 6.2567],
        [ 0.1568]])
tensor([[ 0.0217],
        [ 0.0284],
        [ 0.0409],
        [-0.0034]], requires_grad=True)
tensor([[ 2.6669],
        [55.3329],
        [35.2716],
        [ 1.8691]])
tensor([[ 0.0217],
        [ 0.0284],
        [ 0.0409],
        [-0.0034]], requires_grad=True)
tensor([[  5.6759],
        [103.1152],
        [ 63.5242],
        [  3.3575]])
tensor([[ 0.0217],
        [ 0.0284],
        [ 0.0409],
        [-0.0034]], requires_grad=True)
tensor([[ 2.3299],
        [48.2453],
        [26.8700],
        [ 1.3389]])
tensor([[ 0.0217],
        [ 0.0283],
        [ 0.0408],
        [-0.0034]], requires_grad=True)
tensor([[ 0.9711],
        [19.2861],
        [ 9.4444],
        [ 0.5285]])
tensor([[ 0.0217],
        [ 0.0283],
       

tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[-1.9295],
        [-2.8006],
        [-1.4524],
        [-1.0213]])
tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[-0.4755],
        [ 6.6036],
        [ 0.8751],
        [ 0.1610]])
tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[ 1.2807],
        [66.5447],
        [30.6992],
        [ 1.8903]])
tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[-19.1579],
        [-65.3825],
        [-50.0772],
        [ -5.1355]])
tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[ -8.3215],
        [-47.3077],
        [-39.7204],
        [ -4.0963]])
tensor([[ 0.0219],
        [ 0.0281],
        [ 0.0408],
        [-0.0033]], requires_grad=True)
tensor([[ 4.6048],
      

tensor([[-1.1086],
        [14.3546],
        [10.0462],
        [ 0.5356]])
tensor([[ 0.0220],
        [ 0.0281],
        [ 0.0409],
        [-0.0033]], requires_grad=True)
tensor([[ 0.8216],
        [39.1997],
        [18.8351],
        [ 0.8441]])
tensor([[ 0.0220],
        [ 0.0280],
        [ 0.0409],
        [-0.0033]], requires_grad=True)
tensor([[ -6.6224],
        [-38.2380],
        [-27.4390],
        [ -3.7131]])
tensor([[ 0.0220],
        [ 0.0280],
        [ 0.0409],
        [-0.0033]], requires_grad=True)
tensor([[-1.8349],
        [ 0.8897],
        [-0.0152],
        [-0.5811]])
tensor([[ 0.0220],
        [ 0.0280],
        [ 0.0409],
        [-0.0033]], requires_grad=True)
tensor([[ 0.9249],
        [44.8711],
        [25.1010],
        [ 0.7026]])
tensor([[ 0.0220],
        [ 0.0280],
        [ 0.0409],
        [-0.0033]], requires_grad=True)
tensor([[-4.1282],
        [ 5.3991],
        [-0.6643],
        [-1.4394]])
tensor([[ 0.0220],
        [ 0.0280],
        [ 0

tensor([[-1.2156],
        [-2.6336],
        [-4.5313],
        [-0.8718]])
tensor([[ 0.0221],
        [ 0.0280],
        [ 0.0410],
        [-0.0033]], requires_grad=True)
tensor([[ 0.8311],
        [26.0087],
        [12.6454],
        [ 0.2432]])
tensor([[ 0.0221],
        [ 0.0280],
        [ 0.0410],
        [-0.0033]], requires_grad=True)
tensor([[-0.8665],
        [20.6724],
        [12.0351],
        [-0.3201]])
tensor([[ 0.0221],
        [ 0.0280],
        [ 0.0410],
        [-0.0033]], requires_grad=True)
tensor([[-14.7880],
        [-15.6919],
        [-17.3391],
        [ -2.8902]])
tensor([[ 0.0221],
        [ 0.0279],
        [ 0.0410],
        [-0.0033]], requires_grad=True)
tensor([[-16.8436],
        [-21.3511],
        [-22.1439],
        [ -3.2198]])
tensor([[ 0.0222],
        [ 0.0280],
        [ 0.0410],
        [-0.0033]], requires_grad=True)
tensor([[ 1.3149],
        [29.0759],
        [16.5439],
        [ 0.8204]])
tensor([[ 0.0222],
        [ 0.0280],
       

tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0412],
        [-0.0032]], requires_grad=True)
tensor([[-6.2605],
        [-9.9808],
        [-5.4940],
        [-0.7903]])
tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0412],
        [-0.0032]], requires_grad=True)
tensor([[-7.4825e-01],
        [ 1.7745e+01],
        [ 7.4949e+00],
        [-1.0514e-02]])
tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0413],
        [-0.0032]], requires_grad=True)
tensor([[ 0.8895],
        [27.9212],
        [16.5003],
        [ 0.9548]])
tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0412],
        [-0.0032]], requires_grad=True)
tensor([[-0.9030],
        [ 5.4274],
        [ 4.6425],
        [-0.3854]])
tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0412],
        [-0.0032]], requires_grad=True)
tensor([[ -7.2556],
        [-25.0742],
        [-13.8803],
        [ -2.1624]])
tensor([[ 0.0223],
        [ 0.0282],
        [ 0.0412],
        [-0.0032]], requires_grad=True)
tensor([[ -6.

In [348]:
class LinearNet():
    
    def __init__(train_set, test_set, shape):
        self.shape = shape
        self.w = torch.normal(0, 0.1, size = (4, 1), requires_grad = True)
        self.b = torch.zeros((1, 1), requires_grad = True)
        self.train_set = train_set
        self.test_set = test_set

    def update_params_by_grad(params, learning_rate, batch_size):
        with torch.no_grad():
            for param in params:
                param -= param.grad * learning_rate / batch_size
        for param in params:
            param.grad.zero_()


    def model(X, w, b):
        return torch.matmul(X, w) + b

    #trains the model using SGD and graphs out and outputs running losses 
    def train_SGD(batch_size, learning_rate, num_epochs):  
        data_loader = torch.utils.data.DataLoader(self.train_set, batch_size = batch_size)
        epoch_losses = []
        for epoch in num_epochs:
            running_loss = 0.0
            for i, data in enumerate(data_loader):  
                X, y = data
                pred = model(X, w, b)
                y = y.reshape(pred.shape)
                l_vec = (pred - y)**2
                l = l_vec.sum()
                l.backwards()
                update_params_by_grad([w, b], learning_rate, batch_size)
                running_loss += l.item()
                
                if (i % len(data_loader)) == (len(data_loader) - 1):
                    epoch_losses.append(running_loss/len(data_loader))
                    
        plt.plot(list(range(1, num_epochs + 1)), epoch_losses)
        plt.ylabel("loss")
        plt.xlabel("epoch")
        plt.show()
        plt.savefig()
        
        
        
        
        
        return epoch_losses
                
                
                
                
    
    def test_error(): 


    

tensor([[0.0063]], requires_grad=True)